### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Matr1X-00** [nahueldsanchez/blogpost_qiling_dlink_1#4]
I have two questions:

1. how to fix the broken symbolic link(hedwig.cgi).I use "ln -s" in ubuntu20.04.
2. When I run the 'hedwig.cgi' with qiling,the following error occurred:
`qiling.exception.QlErrorOsType: [!] File does not belong to either 'linux', 'windows', 'freebsd', 'macos', 'ios', 'dos'`
Looking forward to your answer to my question！

**Comment by nahueldsanchez** [comment]
Hi there!,

Looks like you are right. I was able to get the same error. When I wrote the blog post I renamed the file and did not test the link idea. Sorry about that.

I'm not sure how to fix that error. If I found a solution I'll update the blog and let you know.

Thanks!

**Comment by Matr1X-00** [comment]
I have asked the author of qiling.Unfortunately, qiling currently does not support the symbol link.

**Comment by nahueldsanchez** [comment]
Great, thank you for the comment :). I've added a small update to reflect this: https://github.com/nahueldsanchez/blogpost_qiling_dlink_1/commit/892f74d49502706d2c8828bf3f63ed3da10b6b18#diff-5a831ea67cf5cf8703b0de46901ab25bd191f56b320053be9332d9a3b0d01d15.

Thank you!
